name: Build HIZMOS Firmware

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Updated to v4
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Arduino CLI
        uses: arduino/setup-arduino-cli@v1

      - name: Install ESP32 Platform
        run: |
          arduino-cli core update-index --additional-urls https://raw.githubusercontent.com/espressif/arduino-esp32/gh-pages/package_esp32_index.json
          arduino-cli core install esp32:esp32 --additional-urls https://raw.githubusercontent.com/espressif/arduino-esp32/gh-pages/package_esp32_index.json

      - name: Install Libraries
        run: |
          arduino-cli lib install "U8g2"
          arduino-cli lib install "RF24"
          arduino-cli lib install "Adafruit NeoPixel"
          arduino-cli lib install "IRremote"
          arduino-cli lib install "Adafruit PN532"
          arduino-cli lib install "ESP32 BLE Mouse"

      - name: Compile Sketch
        run: |
          mkdir -p build
          arduino-cli compile --fqbn esp32:esp32:esp32s3 --output-dir ./build ./*.ino

      # THIS IS THE FIX: Changed v3 to v4
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: HIZMOS-Firmware
          path: ./build/*.bin
          


